version: '3'
services:
  jmeter-master:
    image: justb4/jmeter:latest
    volumes:
      - ./your-test-plan.jmx:/mnt/jmeter-example.jmx
    command: -Jserver.rmi.ssl.disable=true -n -t /mnt/your-test-plan.jmx -l /mnt/results.jtl

  jmeter-slave:
    image: justb4/jmeter:latest
    volumes:
      - ./your-test-plan.jmx:/mnt/jmeter-example.jmx
    command: -Jserver.rmi.ssl.disable=true -s -Jserver.rmi.localport=4000
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=gatlingdb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=userpassword

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
